apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    spec:
      containers:
        - name: gateway
          image: quay.io/rh-ee-yuewu/catalog-spring-boot:ebf19126e6c148310522473b4c424a2f8d05081d
          resources: {}
