apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    spec:
      containers:
        - name: gateway
          image: quay.io/rh-ee-yuewu/gateway-vertx:a94b77c8aea2bd1b0dff0771bf0447a6db4aa2f8@sha256:5f04438e18d0d40dba407ce2cd4001115296c2bc22c1e9cc92302593de098700
          resources: {}
