apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- digest: sha256:80e10552f300a8b2571d95fe1acafe0d4d3804e83088cbe7f57496a17e2c52e7
  name: quay.io/rh-ee-yuewu/catalog-spring-boot
  newTag: a94b77c8aea2bd1b0dff0771bf0447a6db4aa2f8
